const EErrors = {
    INVALID_TYPES_ERROR: 1,
    INVALID_CREDENTIALS: 2,
    USER_NOT_FOUND: 3,
    PRODUCT_UNAVAILABLE: 4,
    INVALID_TOTAL_AMOUNT: 5,
    UNAUTHENTICATED_USER: 6,
    CART_NOT_FOUND: 7,
    MISSING_FIELDS: 8,
    PRODUCT_EXISTS: 9,
    PRODUCT_NOT_FOUND: 10,

};

export default EErrors;